apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserverml
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: echoserverml
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.0
        imagePullPolicy: Always
        name: echoserverml
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginxml
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserverml
  type: LoadBalancer